# @package _global_
defaults:
  - /trainer: default
  - /loader: default
  - /dataset: akita_benchmark
  - /optimizer: adamw
  - /scheduler: plateau
  - /callbacks: [base, checkpoint]
  - /model: crab

train:
  monitor: val/loss # Needed for plateau scheduler
  mode: min

encoder: id

# we need this for classification!
decoder:
  _name_: contact_map