# @package _global_
defaults:
  - /trainer: default
  - /loader: default
  - /dataset: long_range_benchmark # what is the name of automatic generated dict key?
  - /task: longrange_benchmark
  - /optimizer: adamw
  - /scheduler: plateau
  - /callbacks: [base, checkpoint]

task:
  loss:
    _name_: cross_entropy
  metrics:
    - ${dataset.metric}

train:
  monitor: val/${dataset.metric}
  mode: max

encoder: id

# we need this for classification!
decoder:
  _name_: sequence_snp
  mode: pool