_name_: akita_benchmark
dataset_name: akita_benchmark
dest_path: "/qihao/data/data/benchmark/dnalong"
max_length: 1048576
d_output: ${.${.dataset_name}.classes}
use_padding: True
padding_side: 'left'
add_eos: False
batch_size: 1
train_len: ${.${.dataset_name}.train_len}
__l_max: ${.max_length}
shuffle: true  # set this as default!
akita_benchmark:
  train_len: 450000
  classes: 1
 

#  it seems the train len and class have no meaning here.
