_name_: eqtl_benchmark
dataset_name: eqtl_benchmark
dest_path: null
max_length: 450000
d_output: ${.${.dataset_name}.classes}
use_padding: True
padding_side: 'left'
add_eos: False
batch_size: 1
train_len: ${.${.dataset_name}.train_len}
__l_max: ${.max_length}
shuffle: true  # set this as default!
cell_type: "Adipose_Subcutaneous"

eqtl_benchmark:
  train_len: 450000
  classes: 2

# cell_type:
# ['Adipose_Subcutaneous'
#  'Artery_Tibial'
#  'Cells_Cultured_fibroblasts'
#  'Muscle_Skeletal'
#  'Nerve_Tibial'
#  'Skin_Not_Sun_Exposed_Suprapubic'
#  'Skin_Sun_Exposed_Lower_leg'
#  'Thyroid'
#  'Whole_Blood']
